service: medical-appointments-challenge

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    APPOINTMENT_TABLE_NAME: ${sls:stage}-appointments
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [AppointmentTable, Arn]

    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - Ref: AppointmentTopic

    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource:
        - Fn::GetAtt: [AppointmentQueuePE, Arn]
        - Fn::GetAtt: [AppointmentQueueCL, Arn]

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap:
      type: linked
      setNodeOptions: true
    external:
      - aws-sdk
    packages: external

resources:
  Resources:
    AppointmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-appointments
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    AppointmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${sls:stage}-appointments

    AppointmentQueuePE:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${sls:stage}-appointments-queue-pe

    AppointmentQueueCL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${sls:stage}-appointments-queue-cl

    AppointmentQueuePESubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: AppointmentTopic
        Protocol: sqs
        Endpoint:
          Fn::GetAtt: [AppointmentQueuePE, Arn]
        FilterPolicy:
          countryISO: ["PE"]

    AppointmentQueueCLSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: AppointmentTopic
        Protocol: sqs
        Endpoint:
          Fn::GetAtt: [AppointmentQueueCL, Arn]
        FilterPolicy:
          countryISO: ["CL"]

functions:
  appointment:
    handler: src/infrastructure/lambdas/appointment.handler
    events:
      - http:
          path: appointment
          method: post
          cors: true
    environment:
      DYNAMODB_TABLE_NAME: ${sls:stage}-appointments
      SNS_TOPIC_ARN:
        Ref: AppointmentTopic
